const text = [
    `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla iaculis, justo eu ullamcorper volutpat, ex lacus pellentesque odio, eu porta dolor sem facilisis nisi. Curabitur mattis cursus dolor in posuere. Pellentesque sed neque consectetur, vulputate arcu at, condimentum tortor. In pulvinar iaculis massa ut luctus. In placerat et sapien ut imperdiet. Proin rutrum vulputate lectus, a blandit sapien rhoncus vitae. Aliquam erat volutpat. Nulla id blandit est. Proin facilisis mollis nunc vel aliquet. Pellentesque non tincidunt neque, in convallis odio. Curabitur at metus congue nibh sodales sollicitudin vitae vitae quam. In iaculis neque massa, non porttitor sapien molestie ultrices. In semper pretium ex non facilisis. Praesent dignissim congue magna at sodales. Vestibulum nec iaculis ligula, rutrum lobortis nisl. Maecenas sollicitudin odio in nisl sodales, eget pulvinar magna efficitur.`,
    `Fusce sapien ante, venenatis quis ullamcorper vitae, iaculis sed quam. Pellentesque lorem libero, posuere eu vestibulum id, placerat viverra arcu. Quisque scelerisque, odio nec imperdiet tempus, velit ante fermentum turpis, tristique eleifend tortor enim non nisi. Pellentesque in elit sed nisi rhoncus feugiat. Morbi aliquam, mi a faucibus tincidunt, est lorem euismod mauris, at imperdiet neque dui eget justo. Etiam vitae fringilla nisi, eget feugiat neque. Donec fringilla vestibulum massa viverra sodales. Cras diam nulla, feugiat vitae fringilla et, consectetur tempor augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Integer pellentesque luctus elit at facilisis. Etiam nec mattis erat.`,
    `Duis ultrices vestibulum eros non tincidunt. Ut lobortis non ante sit amet dapibus. Mauris congue hendrerit pharetra. Vestibulum faucibus maximus vestibulum. Suspendisse potenti. Ut ultricies felis id mauris blandit efficitur. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin maximus pellentesque lorem sed lobortis. Donec vel lacinia tellus. Etiam quis libero nec sapien pharetra dapibus. Nullam et libero a orci consectetur hendrerit id eu eros. Aenean quis est fringilla, sodales justo ut, posuere tortor. Aenean laoreet arcu eget tellus ullamcorper, sit amet gravida tortor sagittis. Donec efficitur ipsum in bibendum fermentum.`,
    `Proin quam nulla, feugiat non libero in, posuere aliquet erat. Duis semper porttitor risus quis suscipit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin neque odio, tempus non consectetur sit amet, pretium ut est. Nulla et mauris rhoncus, malesuada mi non, eleifend quam. Morbi mattis hendrerit pharetra. Sed nec nunc nec diam lacinia gravida id ac ante. Suspendisse potenti. Integer at dictum velit, id bibendum nisi. Aliquam blandit est nisl, ut varius nibh egestas sit amet. Vestibulum non fringilla orci. Donec vehicula quam at imperdiet facilisis. In a magna eget neque maximus iaculis. Maecenas eu pharetra sapien. Maecenas erat leo, imperdiet hendrerit sapien et, interdum blandit ex.`,
    `Quisque condimentum orci interdum nisl condimentum aliquet. Nullam id magna bibendum, iaculis lectus volutpat, mollis orci. Suspendisse consectetur ut nisl et tristique. Nam luctus ornare gravida. Vestibulum sit amet nisi lacinia ipsum sollicitudin sollicitudin. Ut nulla tortor, facilisis quis laoreet quis, vulputate in risus. Fusce elementum justo id ligula fringilla semper. Fusce sollicitudin tortor lorem, nec suscipit tortor vulputate sed. Sed sed efficitur massa. Vestibulum sagittis quam mauris, sit amet volutpat nunc tincidunt congue. Praesent aliquet lacus vel pharetra viverra. Vivamus ut nisl at elit tempor ullamcorper. Vestibulum consectetur pharetra sem, volutpat dignissim erat porttitor feugiat. Nulla diam magna, fermentum a risus quis, dapibus aliquet enim. Integer et lorem nisl.`,
    `Suspendisse sit amet tempor elit, vehicula volutpat metus. Nullam non massa a lectus dictum lacinia. Vivamus ut ornare magna, eget blandit nulla. Quisque porttitor nibh ac mi imperdiet dapibus quis vitae est. Vestibulum eget scelerisque arcu. Aenean malesuada, tortor et scelerisque lobortis, ex massa tristique dolor, sollicitudin molestie augue dui in felis. Phasellus scelerisque, lectus et sollicitudin hendrerit, dolor nisl finibus nisi, ac porttitor dolor odio nec arcu. Nulla sodales metus id nibh vulputate, quis lobortis nunc commodo. Praesent euismod vulputate quam, feugiat molestie nunc semper in. Fusce venenatis malesuada vulputate. Nunc ornare risus vehicula, accumsan diam in, fringilla justo.`,
    `Etiam consequat est id justo congue, a pulvinar justo auctor. In condimentum augue sodales finibus posuere. Sed elementum laoreet eros, a sodales orci volutpat quis. Phasellus imperdiet metus nec orci volutpat, a placerat orci efficitur. Integer cursus quam sit amet blandit tincidunt. In volutpat in lorem in eleifend. Integer sit amet libero rutrum, tincidunt magna id, tristique nisl. Phasellus porttitor dolor ut tincidunt maximus. Quisque maximus massa non velit dignissim, in fringilla mauris rhoncus. Sed mollis justo non massa accumsan, sit amet ultrices metus molestie.`,
    `Etiam euismod est interdum mi viverra imperdiet ut eget ligula. In aliquam arcu vitae ipsum tempor sodales. Curabitur pellentesque dignissim mi sed sagittis. Vivamus a mi fringilla, posuere diam vel, tincidunt erat. Pellentesque tempus molestie ante, at tempus odio accumsan ac. Morbi nulla lectus, finibus id pulvinar efficitur, iaculis ut ipsum. Fusce maximus ac leo nec euismod. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed in augue vulputate, mollis nunc sit amet, varius eros. Ut gravida lacus metus, sed pellentesque leo vestibulum et. Aenean vel elit pulvinar est porta fringilla.`,
    `Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut pulvinar justo ante, a commodo lectus volutpat id. Cras ut massa id ex rhoncus ultrices. Mauris in efficitur neque. Donec feugiat efficitur nisl interdum volutpat. Donec vel porttitor nibh, non finibus libero. Ut quis mi pulvinar, vehicula sapien at, efficitur nibh. Nam elementum urna pulvinar imperdiet maximus. Fusce sagittis varius tortor.`
];

const form = document.querySelector(".lorem-form");
const amount = document.getElementById("amount");
const result = document.querySelector(".lorem-text");

form.addEventListener("submit", function(e){
    e.preventDefault();
    const value = parseInt(amount.value);
    const random = Math.floor(Math.random( ) * text.length);

    if(isNaN(value) || value <= 0 || value > 9){
        result.innerHTML = `<p class="result">${text[random]}</p>`;
    }
    else{
        let tempText = text.slice(0,value);
        tempText = tempText.map(function(item){
            return `<p class="result">${item}</p>`;
        })
        .join("");
        result.innerHTML = tempText;
    }
})